---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: airline
  name: airline-canary-deployment
spec:
  selector:
    matchLabels:
      app: airline
  replicas: 2
  template:
    metadata:
      labels:
        app: airline
    spec:
      containers:
      - name: airline
        image: njiang/airline-api:canarydemo-1.0.1
        ports:
        - containerPort: 8080