---
apiVersion: v1
kind: Namespace
metadata:
   name: spinnaker-simple

---
apiVersion: v1
kind: Service
metadata:
  namespace: spinnaker-simple
  name: nginx
spec:
  ports:
    - port: 80
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spinnaker-simple
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80